### PR TITLE
Cleanup Case document upload, download, and delete serverless fns

### PR DESCRIPTION
**Pull request by mythilytm**
## Description
- Serverless does not validate permissions independently for case documents and contact transcripts and recordings service calls to the S3 bucket. These calls are now migrated to Lambdas and will use the permissions mapping set in hrm
- This PR removes the following serverless function used for Case document service calls - `getFileUploadUrl.ts`, `getFileDownloadUrl.ts`, `deleteFile.ts`
- Here are the relevant PRs that replace this functionality :
    - https://github.com/techmatters/hrm/pull/457
    - https://github.com/techmatters/flex-plugins/pull/1651
    - https://github.com/techmatters/flex-plugins/pull/1666 

### Checklist
- [x] Corresponding issue has been opened
- [n/a] New tests added

### Related Issues
Fixes #https://tech-matters.atlassian.net/browse/CHI-2110

### Verification steps
N/A

### CODE REVIEW

**Review by robert-bo-davis — COMMENTED** [review]
We should hold off on merging this until AFTER whatever production deploy actually includes the rest of the flex-plugins and hrm changes to prevent the chance of breaking any existing helpline facing features.

**Comment by mythilytm** [comment]
Sounds good. Will merge this for the next (whichever includes lambda changes) prod deployment.

**Comment by mythilytm** [comment]
@GPaoloni @stephenhand Just a heads up. This a clean up PR that is ready to be merged now

**Review by stephenhand — APPROVED** [review]
❤️

**Pull request merged**
