### PR TITLE
CHI-624 - Created actions to reduce repeated code (DRY pattern)

### PR DESCRIPTION
**Pull request by andvirga**
JIra: [CHI-624](https://bugs.benetech.org/browse/CHI-624)

Changes description:
1. Created three actions to encapsulate common workflow logic:
- `compile-serverless:` builds `.env` file, executes `npm ci`, `npx tsc` and compiles the application.
- `deploy-twilio`: deploys the serverless app using twilio CLI.
- `check-serverless`: Executes the HealthCheck endpoint to verify that the deployed serverless is up and running.

2. Modified workflow to use these actions.
- Each action has a set of inputs and we're passing secrets values (Account SID, Token, etc.) to them.

More information:
I've followed the official [GitHub documentation](https://docs.github.com/en/enterprise-server@2.22/actions/creating-actions/about-actions) to create these actions. This is the maximum that I was able to reduce in the code, however, in the future, you may create one single workflow that triggers several actions to reduce even more the repeated steps. However, that would require a way to execute actions conditionally based on the value of the helpline (that could be provided by an extra input), so keep these in mind to continue improving this code.

This is my last contribution to Aselo and I wanted to mention that it was a great honor for me to had the chance of working on this amazing project! I really hope that Aselo keeps growing and getting implemented in new countries! WIsh you the best of luck!

### CODE REVIEW

**Comment by nickhurlburt** [comment]
@andvirga this looks like a great approach.  Thanks!

**Comment by murilovmachado** [comment]
@nickhurlburt @GPaoloni Do we still need this PR? It seems other [PRs](https://github.com/techmatters/serverless/pull/63) already cover what's in here

**Comment by nickhurlburt** [comment]
Yes, this inspired those others.  @GPaoloni you can close this one when you're ready.

**Comment by GPaoloni** [comment]
Closed in favor of https://github.com/techmatters/serverless/pull/59 and https://github.com/techmatters/serverless/pull/63.

**Pull request closed without merging**
